version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: peeka_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: peekashop
      POSTGRES_USER: peekauser
      POSTGRES_PASSWORD: peekapass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: peeka_rabbitmq
    ports:
      - "5672:5672"       # AMQP
      - "15672:15672"     # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: peeka
      RABBITMQ_DEFAULT_PASS: peeka123
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  orders:
    build: .
    container_name: orders_app
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_HOST: postgres
      DB_USER: peekauser
      DB_PASS: peekapass
      RABBIT_HOST: rabbitmq
    ports:
      - "8080:8080"

volumes:
  pgdata:

