spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/peekashop
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      initialization-fail-timeout: 10000
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: peeka
    password: peeka123
    listener:
      simple:
        default-requeue-rejected: false
        acknowledge-mode: auto

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
